# Generated by Django 5.2.3 on 2025-07-12 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CubeSolve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facelet_string",
                    models.CharField(
                        help_text="The 54-character kociemba facelet string representing the cube state",
                        max_length=54,
                    ),
                ),
                (
                    "solution",
                    models.TextField(
                        help_text="The solution moves as a space-separated string"
                    ),
                ),
                (
                    "move_count",
                    models.IntegerField(help_text="Number of moves in the solution"),
                ),
                (
                    "solve_time_ms",
                    models.FloatField(help_text="Time taken to solve in milliseconds"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the solve was performed",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the client (optional)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cube Solve",
                "verbose_name_plural": "Cube Solves",
                "ordering": ["-timestamp"],
            },
        ),
    ]
